### ISSUE TITLE
PRI is safe and idempotent

### ISSUE THREAD

**Issue by martinthomson** [http2/http2-spec#682]
There seems to be some disagreement about this, but I think that Roy is right.  It's not critical how it is registered, since it shouldn't appear in a valid request anywhere, but it meets the criteria.

**Comment by MikeBishop** [comment]
I really don't think it matters, so I'm fine with it either way.  Theoretically, there may be some compat value in having it listed as safe/idempotent since an intermediary may be more likely to let such methods pass.  But the time slice in which this registry has existed and HTTP/2 hasn't will be miniscule -- I expect any HTTP/2-unaware intermediary won't look at the registry values either.

**Comment by martinthomson** [comment]
To the extent that it matters (i.e., very little, as you point out), I think that the intermediary example weakens the case for safe+idempotent.  I really don't want HTTP/2 to pass an intermediary without triggering some deliberate recognition; that has been the source of some very serious bugs in the past.
