### ISSUE TITLE
padding clarification request

### ISSUE THREAD

**Issue by Scottmitch** [http2/http2-spec#730]
Draft 17 removed the restriction that padding must be zero for headers padding in [section 6.2](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.2) but not for data padding in [section 6.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.1).  Why is this restriction in place for one frame type and not the other?

It seems like we are sending mixed messages.  Prior to draft 17 it seemed like the message was zero should be used perhaps because:
1.True randomness is difficult, and you could be worse off you have bad/predictable "randomness".  See [section 10.7](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-10.7): `In particular, randomized padding with a predictable distribution provides very little protection`.
2. Zero is simple...and there is no proof it is any worse than any other choice?

Would it make sense to either:
1. Require 0 everywhere...because we are confident it is the right thing to do (need justification for this)
2. Require 0 no where, but add a blurb in section 10.7 that 0 may be a good choice and recommended default?  This should also have justification (randomness is hard/expensive, negligible returns, etc...)

**Comment by martinthomson** [comment]
Section 6.2 references 6.1, so that the definition is provided exactly once, that is all.  So we are really taking your option 1:

> Padding fields and flags are identical to those defined for DATA frames (Section 6.1).

Your rationale for why it is zero is basically correct: there is no value in random values, in fact, ignoring the padding could mask errors if padding is being applied incorrectly.  As for security, we have to assume that people have a good secure PRNG or quite a few more things fail.

The note in 10.7 refers to the length of padding, not the actual values in it.

(I know that some people get excited about the possibility of using padding as a covert channel, which would require that implementations ignore padding values.  I don't find that even the slightest bit interesting: we have to assume that use of TLS is sufficient.)

**Comment by Scottmitch** [comment]
Thanks for clarifying!  I see the working group copy is still being maintained as the statement you referred to is not in draft 17.

Is the working group copy intended to be submitted for another draft, or are RFC editors just using this to collect changes?

**Comment by Scottmitch** [comment]
Oops...I now see the statement you referenced at the bottom of the HEADERS section...which was there prior to draft 17...makes sense to remove the redundancies.
