### ISSUE TITLE
question about  stream dependent on a not exists parent

### ISSUE THREAD

**Issue by byronhe** [http2/http2-spec#764]
I have question about the following paragraph in rfc 7540:

> 5.3.1.  Stream Dependencies
>   A stream that depends on another stream is a dependent stream.  The
>    stream upon which a stream is dependent is a parent stream.  A
>    dependency on a stream that is not currently in the tree -- such as a
>    stream in the "idle" state -- results in that stream being given a
>    default priority (Section 5.3.5).
> 

which does ' that stream ' mean ? the stream in frame header ? or the  dependency stream in "idle" state ?
 
for example, if stream 6 in open state, but stream 7 not exist ( in idle state ). then peer send a  PRIORITY on stream 6 with dependency = 7  , weight = 100, exclusive  = true,

which should i do ?

1.  allocate a new node for stream 7 in my depenency tree ,  then do normal PRIORITY processing.
2.  let stream 6 dependent on stream 0 (root),  still using weight = 100, exclusive = true.
3.  let stream 6 dependent on stream 0, with default priority weight = 100, exclusive = false.
4.  let stream 6 dependent on stream 0, with default priority weight = 16, exclusive = false.

**Comment by byronhe** [comment]
nginx choose 3  :
https://github.com/nginx/nginx/blob/master/src/http/v2/ngx_http_v2.c#L4390

and proxygen choose 2 :
https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/session/HTTP2PriorityQueue.cpp#L530

trafficserver choose 2:
https://github.com/apache/trafficserver/blob/master/proxy/http2/Http2DependencyTree.h#L170


only nghttp2 choose 1:

https://github.com/nghttp2/nghttp2/blob/master/lib/nghttp2_session.c#L765

**Comment by Lukasa** [comment]
If that's the case, I'd say nginx, proxygen, and trafficserver are wrong. :wink:

So, doing 2 is *clearly* wrong because asking for stream 6 to be an exclusive dependant of stream 7 is causing you to make stream 6 an exclusive dependant of the root stream. This forces *all other streams* to become dependants of stream 6, which is clearly utterly incorrect. 2 is wrong.

Doing 3 is *less* wrong but it leads to overweighting of stream 6. While the other streams continue to sit in the same place in the tree, stream 6 should be being given 100% of the weight of its parent stream, stream 7, which should be the default weight. Instead, it's being given proportionally more of the weight (the proportion depends on the weights of the other streams).

Doing 4 is the least wrong of the collection: it leads to the appropriate weights *at the moment*. It becomes wrong if stream 8 is immediately made a child of stream 7, where streams 6 and 8 should share the total weight of their parent stream but will instead get a bit more resources. But it's the closest to correct in the first instance.

As a note, the Python priority tree implementation also does (1).

**Comment by byronhe** [comment]
ok ,  i agree, we should do 1. 
thanks.

**Comment by Scottmitch** [comment]
There is at least 1 discussion on this topic on the mailing list [1]. It is long but the conclusion is priority frames are not meant to change the state of a stream and in practice it the semantics are better represented if the priority state and stream state can be decoupled to account for this. Keep in mind you may want to only keep a limited amount of state for priority as it is only advisory, but this is not the case for "active streams" which the amount of state is limited by `SETTINGS_MAX_CONCURRENT_STREAMS`.

[1] https://lists.w3.org/Archives/Public/ietf-http-wg/2017JanMar/0046.html
