### ISSUE TITLE
HPACK Dynamic Table Size and Lazy Huffman Decoding

### ISSUE THREAD

**Issue by samoconnor** [http2/http2-spec#767]
The [FAQ says](https://http2.github.io/faq/#why-is-there-an-eos-symbol-in-hpack) that because of the padding in HPACK’s huffman encoding...
> many headers can be interpreted without being Huffman decoded

Following this logic we have implemented a lazy HPACK decoder that defers Huffman decoding until a string needs to be interpreted or compared to a non-ecoded string. In the case of comparison we only decode as many bytes as needed to find the first mismatch.

However, it seems that we will have to huffman decode most strings anyway in order to follow the spec with regard to calculate dynamic table size.

[RFC7541 4.1](https://httpwg.org/specs/rfc7541.html#rfc.section.4.1) says that headers have to be huffman decoded in order to calculate the dynamic table size:
> The size of an entry is calculated using the length of its name and value without any Huffman encoding applied.

It is inefficient to have to compute a fictional "table size" using the decoded size +32, when our actual  Huffman encoded table size is smaller.

[RFC7541 4.4](https://httpwg.org/specs/rfc7541.html#rfc.section.4.4) says that entries "are" evicted in certain circumstances. Note that it does not say "MUST be" or "SHOULD be":

> Before a new entry is added to the dynamic table, entries **are** evicted from the end of the dynamic table until the size of the dynamic table is less than or equal to (maximum size - new entry size) or until the table is empty.

Maybe this should be relaxed to say "SHOULD be evicted" to allow lazy implementations that might prefer to defer eviction to a later time, or use a more relaxed threshold. For example, an implementation that ueses the huffman encoded size to compute table size will never prematurely evict entries that the encoder would later rely on. Instead it will harmlessly retain some entries that the encoder would assume had been evicted.

Is there any reason that a decoder MUST not leave entries in the dynamic table after the strict interpretation of the table size calculation would have evicted them?

It seems that the only way an encoder could know that a decoder was being lazy and not evicting entries is by sending a deliberately out of bounds index and checking for a decoding error.

**Comment by samoconnor** [comment]
https://tools.ietf.org/html/rfc7541#section-2.3.3
> Indices strictly greater than the sum of the lengths of both tables MUST be treated as a decoding error.

This seems to imply that entries MUST be evicted according to the table size calculated exactly per [4.1](https://httpwg.org/specs/rfc7541.html#rfc.section.4.1).

**Comment by martinthomson** [comment]
@MikeBishop pointed out that this isn't much different than the encoder using less than the full size of the table.  Aside from the requirement in Section 2.3.3 you point out, there aren't any strong reasons to strictly evict.  In fact, as long as the encoder behaves, you should never encounter the decoding error - and few encoders will bother to check that you are generating a decoder error faithfully.

The real problem comes when the values are bigger when encoded.  If you get a lot of 0xff and friends (which aren't valid ASCII in terms of most header fields), then the Huffman-encoded string will be longer than the actual string.  That will get you into trouble because you will appear not to have space when you really should.  You could get tons of CRLF octets, which use 30 bits each, multiplying the space you use by almost 4.  You will think that you have run out of space, when the encoder thinks it still has room.

You can't assume encoders won't expand strings, sadly.

So aside from multiplying the space you have by 30/8, which is not ideal, it's probably best to look for long encodings.  All the long encodings start with 7 1s (`0xfe | ?`).  But scanning for those efficiently is tricky.  Best I can think of is a decoder pass without saving the output; I know some implementations do that to count sizes.

**Comment by samoconnor** [comment]
Thanks for taking the time to share your knowledge @martinthomson.

I'm working on code for Julia, which is targeted at machines that typically have lots of RAM.
My current experiment,  following in the pattern of our [existing lazy HTTP/1.1 parser](https://github.com/JuliaWeb/HTTP.jl/blob/so/lazyprep/src/LazyHTTP.jl), is to build [a HPACK decoder that is as lazy as possible](https://github.com/JuliaWeb/HTTP.jl/blob/so/lazyprep/src/HPack.jl). Having a largish fixed size buffer for the dynamic table is fine at least for now. The plan is to eventually compare performance with various aspects of laziness turned on and off to figure the best compromises.

I have to say that the scheme of computing a fictional number of bytes consumed seems convoluted and unhelpful. Surely the same intent could be achieved by using the actual on-the-wire number of bytes. The idea of a constrained table size seems to be aimed at helping IOT-type devices with constrained memory. Surely if effort is being invested in RAM efficient implementations for these small systems they would keep the table in compressed form anyway?

**Comment by martinthomson** [comment]
We debated this point at the time we decided to do this and settled on counting the decoded size; it wasn't an easy call.  The time-space trade-offs never are.

Closing this, since this repo is long dead.  If you want to ask any more questions, I'd recommend going direct to the working group using email: ietf-http-wg@w3.org

**Comment by samoconnor** [comment]
Thanks @martinthomson
